services:
  base:
    image: pichacky-base
    build:
      context: ./
      dockerfile: Dockerfile

  web:
    image: pichacky-base
    ports:
      - 8000:8000
    volumes:
      - .:/app
    env_file:
      - .env
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000

  tests:
    image: pichacky-base
    volumes:
      - .:/app
    working_dir: /app
    command: python -m unittest -v
