apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pichacky-set
spec:
  selector:
    matchLabels:
      app: pichacky
  serviceName: "pichacy-web"
  replicas: 4
  template:
    metadata:
      labels:
        app: pichacky
    spec:
      containers:
      - name: pichacky-web
        image: registry.digitalocean.com/my-container-hub/pichacky:by_jenkins
        imagePullPolicy: Always
        command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
        volumeMounts:
        - mountPath: "/data"
          name: pichacky-pvc
        env:
        - name: DB_DIR
          value: "/data"
        - name: DEBUG
          value: "0"
  volumeClaimTemplates:
  - metadata:
      name: pichacky-pvc
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: do-block-storage




