# Generated by Django 3.1.2 on 2020-10-17 21:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201017_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='action',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='action',
            unique_together={('date', 'type')},
        ),
        migrations.RemoveField(
            model_name='action',
            name='timestamp',
        ),
    ]
